<a href="https://colab.research.google.com/github/srivastavask/Pytorch-Tutorial/blob/main/Pytorch_tut1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip list

In [ ]:
2+2

4

In [1]:
import torch
import numpy as np

In [6]:
np1 = np.random.rand(3,4)
print(np1)
print(np1.dtype)

[[0.07496242 0.34667542 0.2044547  0.16806607]
 [0.89325342 0.38235252 0.46877853 0.92635504]
 [0.93105457 0.18573583 0.87051025 0.71034048]]
float64


In [9]:
tensor_2d = torch.randn(3,4)
print(tensor_2d)
print(tensor_2d.dtype)

tensor([[ 1.5213, -0.4708,  0.2208, -0.0954],
        [ 1.4028,  1.1479,  1.8350, -0.9660],
        [ 0.0335, -1.0204, -0.2636,  0.5637]])
torch.float32


In [11]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0750, 0.3467, 0.2045, 0.1681],
        [0.8933, 0.3824, 0.4688, 0.9264],
        [0.9311, 0.1857, 0.8705, 0.7103]], dtype=torch.float64)

In [13]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
my_shape = my_torch.reshape(2,5)
my_shape

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [22]:
my_torch1 = torch.arange(15)
my_shape1 = my_torch1.reshape(3,-1)
my_shape1

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [23]:
my_torch2 = torch.arange(10)
my_shape2 = my_torch2.reshape(-1,5)
my_shape2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
my_torch3 = torch.arange(10)
my_shape3 = my_torch2.reshape(2,5)
my_shape3

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [28]:
my_torch2[1] = 4141
my_shape3

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [29]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
my_torch5[7]

tensor(7)

In [35]:
my_torch6 = my_torch5.reshape(5,2)

In [46]:
my_torch6[:,1]

tensor([1, 3, 5, 7, 9])

In [47]:
my_torch6[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [48]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [49]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [51]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [52]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [53]:
# tensor reassignment
tensor_a = tensor_a.add(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])

In [54]:
tensor_a = tensor_a.add_(tensor_b)
tensor_a

tensor([11, 14, 17, 20])

Creating a NN using torch

In [55]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [57]:
class Model(nn.Module):
  def __init__(self, in_features=4, h1=8, h2=9, out_features=3):
    super().__init__()  #instantiate nn model
    self.fc1 = nn.Linear(in_features, h1)
    self.fc2 = nn.Linear(h1, h2)
    self.out = nn.Linear(h2, out_features)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.out(x)
    return x

In [58]:
# picking a random seed for randamization
torch.manual_seed(41)
model = Model()

In [59]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [61]:
url = 'https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv'
my_df = pd.read_csv(url)
my_df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [62]:
# change last column
my_df['species'] = my_df['species'].replace('setosa', 0.0)
my_df['species'] = my_df['species'].replace('versicolor', 1.0)
my_df['species'] = my_df['species'].replace('virginica', 2.0)
my_df

<ipython-input-62-31d2ab34cca2>:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  my_df['species'] = my_df['species'].replace('virginica', 2.0)


sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2      0.0
1             4.9          3.0           1.4          0.2      0.0
2             4.7          3.2           1.3          0.2      0.0
3             4.6          3.1           1.5          0.2      0.0
4             5.0          3.6           1.4          0.2      0.0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3      2.0
146           6.3          2.5           5.0          1.9      2.0
147           6.5          3.0           5.2          2.0      2.0
148           6.2          3.4           5.4          2.3      2.0
149           5.9          3.0           5.1          1.8      2.0

[150 rows x 5 columns]